# service.yaml - SWE645 HW2
# Exposes the Student Survey app via LoadBalancer

apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-service
spec:
  type: NodePort
  selector:
    app: simple-webapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
